from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from api.models import Category, Product


PRODUCTS_DATA = [
    {
        'category': 'electronics',
        'name': 'Aura Wireless Headphones',
        'slug': 'aura-wireless-headphones',
        'description': 'Premium noise-cancelling wireless headphones with 40-hour battery life and crystal-clear audio.',
        'price': 84999,
        'compare_price': 111999,
        'image_url': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
        'stock': 50,
        'rating': 4.8,
        'review_count': 234,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'electronics',
        'name': 'Luxe Smart Watch Pro',
        'slug': 'luxe-smart-watch-pro',
        'description': 'Elegant smartwatch with health tracking, sapphire glass, and titanium finish.',
        'price': 125999,
        'compare_price': 153999,
        'image_url': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
        'stock': 35,
        'rating': 4.9,
        'review_count': 189,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'electronics',
        'name': 'Crystal Bluetooth Speaker',
        'slug': 'crystal-bluetooth-speaker',
        'description': '360° surround sound speaker with ambient LED lighting and waterproof design.',
        'price': 49999,
        'image_url': 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600',
        'stock': 80,
        'rating': 4.6,
        'review_count': 156,
        'is_featured': True,
    },
    {
        'category': 'fashion',
        'name': 'Velvet Evening Blazer',
        'slug': 'velvet-evening-blazer',
        'description': 'Handcrafted Italian velvet blazer with silk lining. Perfect for formal occasions.',
        'price': 108999,
        'compare_price': 145999,
        'image_url': 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600',
        'stock': 25,
        'rating': 4.7,
        'review_count': 98,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'fashion',
        'name': 'Cashmere Overcoat',
        'slug': 'cashmere-overcoat',
        'description': 'Luxurious 100% cashmere overcoat with minimalist design and exceptional warmth.',
        'price': 167999,
        'image_url': 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600',
        'stock': 15,
        'rating': 4.9,
        'review_count': 67,
        'is_featured': True,
    },
    {
        'category': 'fashion',
        'name': 'Silk Scarf Collection',
        'slug': 'silk-scarf-collection',
        'description': 'Hand-painted silk scarf with gold thread accents. A timeless accessory.',
        'price': 35999,
        'compare_price': 45999,
        'image_url': 'https://images.unsplash.com/photo-1601924999337-eeae0d3b0f0e?w=600',
        'stock': 60,
        'rating': 4.5,
        'review_count': 112,
        'is_new': True,
    },
    {
        'category': 'home',
        'name': 'Marble Table Lamp',
        'slug': 'marble-table-lamp',
        'description': 'Sculptural table lamp with Carrara marble base and brushed brass accents.',
        'price': 69999,
        'image_url': 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600',
        'stock': 40,
        'rating': 4.8,
        'review_count': 78,
        'is_featured': True,
    },
    {
        'category': 'home',
        'name': 'Artisan Ceramic Vase Set',
        'slug': 'artisan-ceramic-vase-set',
        'description': 'Set of three hand-thrown ceramic vases with organic glaze finishes.',
        'price': 44999,
        'compare_price': 55999,
        'image_url': 'https://images.unsplash.com/photo-1578500494198-246f622d47b6?w=600',
        'stock': 45,
        'rating': 4.6,
        'review_count': 45,
        'is_new': True,
    },
    {
        'category': 'home',
        'name': 'Premium Linen Bedding Set',
        'slug': 'premium-linen-bedding-set',
        'description': 'European flax linen bedding set. Breathable, durable, and gets softer with every wash.',
        'price': 91999,
        'image_url': 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600',
        'stock': 30,
        'rating': 4.7,
        'review_count': 203,
        'is_featured': True,
    },
    {
        'category': 'beauty',
        'name': 'Gold Elixir Serum',
        'slug': 'gold-elixir-serum',
        'description': '24K gold-infused anti-aging serum with hyaluronic acid and botanical extracts.',
        'price': 24999,
        'compare_price': 33999,
        'image_url': 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
        'stock': 100,
        'rating': 4.8,
        'review_count': 312,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'beauty',
        'name': 'Signature Perfume Collection',
        'slug': 'signature-perfume-collection',
        'description': 'Exclusive fragrance trio featuring notes of oud, rose, and amber.',
        'price': 54999,
        'image_url': 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',
        'stock': 55,
        'rating': 4.9,
        'review_count': 178,
        'is_featured': True,
    },
    {
        'category': 'beauty',
        'name': 'Luxury Skincare Ritual Set',
        'slug': 'luxury-skincare-ritual-set',
        'description': 'Complete 5-step skincare ritual with cleanser, toner, serum, cream, and eye treatment.',
        'price': 76999,
        'compare_price': 97999,
        'image_url': 'https://images.unsplash.com/photo-1556228578-0d53b4a4bb9e?w=600',
        'stock': 40,
        'rating': 4.7,
        'review_count': 145,
    },
    {
        'category': 'accessories',
        'name': 'Italian Leather Tote',
        'slug': 'italian-leather-tote',
        'description': 'Hand-stitched full-grain leather tote with suede interior and gold hardware.',
        'price': 118999,
        'image_url': 'https://images.unsplash.com/photo-1584917865442-de89df76fd3e?w=600',
        'stock': 20,
        'rating': 4.9,
        'review_count': 89,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'accessories',
        'name': 'Titanium Sunglasses',
        'slug': 'titanium-sunglasses',
        'description': 'Ultra-light titanium frame sunglasses with polarized lenses and anti-reflective coating.',
        'price': 58999,
        'compare_price': 77999,
        'image_url': 'https://images.unsplash.com/photo-1572635196233-15949d09f5b0?w=600',
        'stock': 65,
        'rating': 4.6,
        'review_count': 134,
    },
    {
        'category': 'accessories',
        'name': 'Swiss Automatic Watch',
        'slug': 'swiss-automatic-watch',
        'description': 'Swiss-made automatic movement watch with sapphire crystal and exhibition caseback.',
        'price': 363999,
        'image_url': 'https://images.unsplash.com/photo-1524592312887-2fd9c4c9c0c0?w=600',
        'stock': 10,
        'rating': 5.0,
        'review_count': 42,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'electronics',
        'name': 'Pro Camera Drone',
        'slug': 'pro-camera-drone',
        'description': '4K HDR camera drone with 3-axis gimbal, obstacle avoidance, and 45-min flight time.',
        'price': 251999,
        'compare_price': 307999,
        'image_url': 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600',
        'stock': 18,
        'rating': 4.7,
        'review_count': 76,
        'is_new': True,
    },
    {
        'category': 'electronics',
        'name': 'Nova Wireless Earbuds',
        'slug': 'nova-wireless-earbuds',
        'description': 'Compact true wireless earbuds with deep bass, touch controls, and 24-hour total battery.',
        'price': 1499,
        'compare_price': 2499,
        'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
        'stock': 120,
        'rating': 4.5,
        'review_count': 412,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'electronics',
        'name': 'Pulse Fitness Band',
        'slug': 'pulse-fitness-band',
        'description': 'Lightweight fitness tracker with heart rate monitor, SpO2, and 7-day battery life.',
        'price': 829,
        'compare_price': 1299,
        'image_url': 'https://images.unsplash.com/photo-1575311373937-040b8e1e99df?w=600',
        'stock': 200,
        'rating': 4.4,
        'review_count': 267,
        'is_featured': True,
        'is_new': True,
    },
    {
        'category': 'fashion',
        'name': 'Classic Cotton T-Shirt',
        'slug': 'classic-cotton-t-shirt',
        'description': 'Premium combed cotton crew neck tee. Soft, breathable, and perfect for everyday wear.',
        'price': 799,
        'compare_price': 1199,
        'image_url': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
        'stock': 150,
        'rating': 4.3,
        'review_count': 189,
        'is_new': True,
    },
    {
        'category': 'fashion',
        'name': 'Slim Fit Denim Jeans',
        'slug': 'slim-fit-denim-jeans',
        'description': 'Stretch denim jeans with modern slim fit and durable stitching.',
        'price': 1799,
        'compare_price': 2799,
        'image_url': 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
        'stock': 90,
        'rating': 4.6,
        'review_count': 143,
        'is_featured': True,
    },
    {
        'category': 'home',
        'name': 'Aroma Diffuser Lamp',
        'slug': 'aroma-diffuser-lamp',
        'description': 'Ultrasonic aroma diffuser with warm LED mood lighting and auto shut-off.',
        'price': 1299,
        'compare_price': 1999,
        'image_url': 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600',
        'stock': 75,
        'rating': 4.5,
        'review_count': 98,
        'is_new': True,
    },
    {
        'category': 'beauty',
        'name': 'Hydrating Face Moisturizer',
        'slug': 'hydrating-face-moisturizer',
        'description': 'Daily moisturizer with vitamin E and aloe vera for all skin types.',
        'price': 499,
        'compare_price': 799,
        'image_url': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
        'stock': 180,
        'rating': 4.4,
        'review_count': 221,
        'is_new': True,
    },
    {
        'category': 'accessories',
        'name': 'Urban Leather Wallet',
        'slug': 'urban-leather-wallet',
        'description': 'Minimal bi-fold wallet with RFID protection and multiple card slots.',
        'price': 999,
        'compare_price': 1499,
        'image_url': 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600',
        'stock': 110,
        'rating': 4.5,
        'review_count': 76,
        'is_featured': True,
    },
]

CATEGORIES = [
    {'name': 'Electronics', 'slug': 'electronics', 'description': 'Cutting-edge technology and premium gadgets'},
    {'name': 'Fashion', 'slug': 'fashion', 'description': 'Timeless elegance and contemporary style'},
    {'name': 'Home & Living', 'slug': 'home', 'description': 'Curated pieces to elevate your living space'},
    {'name': 'Beauty', 'slug': 'beauty', 'description': 'Luxury skincare and fragrance collections'},
    {'name': 'Accessories', 'slug': 'accessories', 'description': 'Finishing touches that define your look'},
]


class Command(BaseCommand):
    help = 'Seed the database with sample products and categories'

    def handle(self, *args, **options):
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@ukservices.com', 'admin123')
            self.stdout.write(self.style.SUCCESS('Created admin user (admin/admin123)'))

        for cat_data in CATEGORIES:
            Category.objects.get_or_create(slug=cat_data['slug'], defaults=cat_data)

        for prod_data in PRODUCTS_DATA:
            cat_slug = prod_data.pop('category')
            category = Category.objects.get(slug=cat_slug)
            Product.objects.update_or_create(
                slug=prod_data['slug'],
                defaults={**prod_data, 'category': category},
            )

        self.stdout.write(self.style.SUCCESS(f'Seeded {len(CATEGORIES)} categories and {len(PRODUCTS_DATA)} products'))
